JuliaPackaging/Requires.jl

src/lazymod.jl

Also, shouldn't you use gensym() for the function name and then return the load function? This will reduce naming conflicts, and the syntax will be changed to an acceptable:
```Julia
imagesload = @lazymod Images
```

Without Main, Module can't be found

---

src/lazymod.jl

This gets rid of a 0.4 deprecation warning for me... does it create any problems that I don't foresee?

changed require to eval import

---

src/getthing.jl

This should work with no warnings on release and nightly now.
There are no package tests but it worked properly in LightGraphs.

Fix field access deprecation warning

---

src/Requires.jl
src/oldcall.jl
src/require.jl

Fixes the longer example in #30. The problem is that `Base.require` uses eval and thus switches into a newer age. We need to provide enough tasks so that we can switch back (the previous tasks get blocked while doing so).
cc: @davidanthoff

Uses multiple tasks for calling into an old world

---

src/oldcall.jl

Otherwise we seem to prevent other tasks from running.
fixes #34

yield before processing calling f in oldcall

---

src/require.jl

This is the small patch I [semi-]guess-and-checked my way to resolving a similar issue as #48, as mentioned in [this comment](https://github.com/MikeInnes/Requires.jl/issues/48#issuecomment-404381545).

Interpolate PkgId expression, working around #48

---

test/REQUIRE
test/runtests.jl

Adds the tests related to issue #48 and the change made in #49.
~I tried making sure these test fail when the change in #48 is reverted, but I couldn't get it to trigger. I don't know if I'm just invoking `pkg> test Requires` from the wrong environment (i.e. it's just pulling Requires v0.5.2 back in) or maybe there's a difference related to Pkg2 vs Pkg3 style environments — I was initially running into the bug for some code I was adding a `Project.toml` and trying to sort out how sub-projects should be structured...~ (See comments below.)

Add test for #48

---

README.md

There still seems to be some confusion about how to use this (https://github.com/MikeInnes/Requires.jl/pull/46#issuecomment-415725554), so let's document the new syntax in the README. CC @davidavdav

Update README for the new UUID & __init__ syntax

---

src/require.jl

Before:
```
julia> @time Base.invokelatest(Requires.loadpkg, pkgids[4])
0.051562 seconds (125.03 k allocations: 6.398 MiB)
```
after:
```
julia> @time Base.invokelatest(Requires.loadpkg, pkgids[4])
0.025036 seconds (31.71 k allocations: 1.527 MiB)
```

improve callback performance

---

Project.toml
README.md
src/Requires.jl
src/require.jl

This is motivated by wanting integration with Revise. However, I implemented it as a general mechanism in case other packages want similar integration. The companion PR is in Revise https://github.com/timholy/Revise.jl/pull/387.
Note that this includes a couple of updates, of which the only important one is upper-bounding Julia at version 1.x. This is necessary for automatic merging of registrations.

Support package notifications

---

src/Requires.jl
src/require.jl

This shaves a few percent off the time needed for `using Images`. Not a big deal, but certainly doesn't hurt.

Small performance improvements

---

src/Requires.jl
src/require.jl

This shaves about 30ms off the time to load a simple Requires-dependent package; not a ton, but pretty consistent and worth having given how many packages use Requires.
This does not eliminate all runtime inference when using Requires; `get!` simply refuses to completely precompile (probably https://github.com/JuliaLang/julia/pull/32705?), although this helps.

Add more precompile and fix an inference problem

---

src/Requires.jl
test/runtests.jl

This reverts to using the normal include() mechanism in @-require, and
only falling back to the macro expansion-time include_string if the file
doesn't exist at runtime.
I think this implements the last changes requested in #85

Use cached content in @ include only as a fallback

---

src/Requires.jl
src/require.jl
test/runtests.jl

This PR adds an `@include` macro which behaves like `include`, but is more compatible with compiling a sysimg.
Separately, it also adds a hook to replace `include` statements in `@require` block with `@include`. This risks being a bit magical but shouldn't affect normal usage at all, only sysimg usage. The main edge case is recursive `include` during sysimg compilation (e.g. file included by Requires has another `include` in it). Since this is pretty uncommon, it should make most Requires usage just work with sysimg building.

Include macro for building sysimgs

---

src/require.jl

This produces better pretty printing of the error message for logging
backends which support the standard exception field.
Eg with `TerminalLoggers.TerminalLogger`, new printing:
```
┌ Warning: Error requiring DataSets from MyTest
│   exception =
│    oh noes
│    Stacktrace:
│     [1] error(::String) at ./error.jl:33
│     [2] top-level scope at /home/chris/tmp/MyTest/src/MyTest.jl:13
│     [3] eval at ./boot.jl:331 [inlined]
│     [4] eval at /home/chris/tmp/MyTest/src/MyTest.jl:1 [inlined]
│     [5] (::MyTest.var"#3#6")() at /home/chris/.julia/dev/Requires/src/require.jl:94
│     [6] err(::Any, ::Module, ::String) at /home/chris/.julia/dev/Requires/src/require.jl:42
│     [7] (::MyTest.var"#2#5")() at /home/chris/.julia/dev/Requires/src/require.jl:93
...
```
vs old printing:
```
┌ …
```

Use standard `exception` field for require warning

---

src/Requires.jl
src/require.jl

The following benchmark:
```julia
julia> using Example
julia> id = Base.module_keys[Example]
Example [7876af07-990d-54b4-ab0e-23690620f79a]
julia> @time begin
@eval module SomeMod
using Requires
__init__() = @require Example="7876af07-990d-54b4-ab0e-23690620f79a" f(x) = x^2
end
end
0.335103 seconds (512.40 k allocations: 30.980 MiB, 8.35% gc time)
Main.SomeMod
```
has substantial latency. This PR cuts it to less than half:
0.145450 seconds (178.21 k allocations: 10.709 MiB)
It also makes the precompiles less fragile.

Reduce latency

---

.github/workflows/CI.yml
src/require.jl

Other packages can set up callbacks to be notified about `@require`
blocks. Previously, the notification was issued before Requires
set the `const` for the module name in the package that set up
the `@require` block. This PR changes it so that those notifications
are sent afterwards, thus ensuring that the `const` will be defined
by the time "consumers" get notified.
This is a potentially-breaking change. Since it would cause huge
`[compat]` churn to bump the major version, given the considerations
below I think we can safely use a minor-version bump:
- Requires' README does not promise any particular ordering.
- This ordering seems to make a bit more sense.
- Revise appears to be the only user of this functionality based on
the lack of any other entries in `notified_pkgs` and a search of …

Issue notifications after loading package

---

src/Requires.jl
src/require.jl

Adds a debug log so you can monitor `@require`s that get triggered and the time spent running code
```julia
julia> ENV["JULIA_DEBUG"]="Requires"
"Requires"
julia> using Foo
┌ Debug: Requires conditionally ran code in 0.917808094 seconds: `Ratios` detected `FixedPointNumbers`
└ @ Requires ~/.julia/packages/Ratios/xLeZh/src/Ratios.jl:123
┌ Debug: Requires conditionally ran code in 0.531145239 seconds: `ArrayInterface` detected `SuiteSparse`
└ @ Requires ~/.julia/packages/ArrayInterface/mI7ab/src/ArrayInterface.jl:675
┌ Debug: Requires conditionally ran code in 0.002734456 seconds: `ArrayInterface` detected `Adapt`
└ @ Requires ~/.julia/packages/ArrayInterface/mI7ab/src/ArrayInterface.jl:760
┌ Debug: Requires conditionally ran code in 0.029623663 seconds: `ArrayInterface` detected …
```

Add debug log for monitoring `@require` time

---

README.md

Should address #113
This PR assumes that Package Extensions is indeed the recommended route now.
If that is not the case, then the README should provide users with guidance
about when to use which approach.
For reference, there is a discourse discussion of how to serve both Julia 1.9 and above as well as earlier versions:
https://discourse.julialang.org/t/package-extensions-for-julia-1-9/93397
(I share Tim Holy's view there that it is not worth the effort, but if someone wants to put in the effort to update the README here to document it then please do!)

Steer readers to Package Extensions

---

test/runtests.jl

1.12 is more restrictive when it comes to world ages, running the full tests in a `@testset` does not allow us to hit top-level to "refresh" the world age

avoid running code that needs to be running at top level in a test
